<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.sebastian-daschner</groupId>
  <artifactId>favorite-coffee</artifactId>
  <version>1.0</version>
  <properties>
    <maven.compiler.target>17</maven.compiler.target>
    <quarkus.version>2.13.3.Final</quarkus.version>
    <maven.compiler.source>17</maven.compiler.source>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-api</artifactId>
        <version>5.7.2</version>
        <scope>test</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-qute</artifactId>
      <version>2.13.3.Final</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-ide-launcher</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.jboss.spec.javax.xml.bind</groupId>
          <artifactId>jboss-jaxb-api_2.3_spec</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.smallrye.common</groupId>
          <artifactId>smallrye-common-io</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.sun.activation</groupId>
          <artifactId>jakarta.activation</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.jboss.logging</groupId>
          <artifactId>jboss-logging-annotations</artifactId>
        </exclusion>
      
        <exclusion>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-arc</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-core</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-resteasy</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.smallrye.common</groupId>
          <artifactId>smallrye-common-classloader</artifactId>
        </exclusion>
        <exclusion>
          <groupId>jakarta.annotation</groupId>
          <artifactId>jakarta.annotation-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>jakarta.inject</groupId>
          <artifactId>jakarta.inject-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>jakarta.validation</groupId>
          <artifactId>jakarta.validation-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.microprofile.config</groupId>
          <artifactId>microprofile-config-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.jboss.logging</groupId>
          <artifactId>jboss-logging</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.slf4j</groupId>
          <artifactId>slf4j-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.wildfly.common</groupId>
          <artifactId>wildfly-common</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-jsonb</artifactId>
      <version>2.13.3.Final</version>
      <scope>compile</scope>
          <exclusions>
        <exclusion>
          <groupId>jakarta.json.bind</groupId>
          <artifactId>jakarta.json.bind-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-health</artifactId>
      <version>2.13.3.Final</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>io.smallrye.reactive</groupId>
          <artifactId>smallrye-mutiny-vertx-uri-template</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.smallrye.reactive</groupId>
          <artifactId>smallrye-mutiny-vertx-bridge-common</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.vertx</groupId>
          <artifactId>vertx-uri-template</artifactId>
        </exclusion>
      
        <exclusion>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-core</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.github.crac</groupId>
          <artifactId>org-crac</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-buffer</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-codec</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-codec-http</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-codec-http2</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-common</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-resolver</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-transport</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-jsonp</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-vertx-http</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.smallrye</groupId>
          <artifactId>smallrye-context-propagation</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.smallrye.common</groupId>
          <artifactId>smallrye-common-annotation</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.smallrye.common</groupId>
          <artifactId>smallrye-common-constraint</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.smallrye.common</groupId>
          <artifactId>smallrye-common-vertx-context</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.vertx</groupId>
          <artifactId>vertx-core</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.vertx</groupId>
          <artifactId>vertx-web</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.neo4j</groupId>
      <artifactId>neo4j-ogm-quarkus</artifactId>
      <version>2.1.0</version>
      <scope>compile</scope>
          <exclusions>
        <exclusion>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-annotations</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-databind</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.neo4j</groupId>
          <artifactId>neo4j-ogm-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.neo4j.driver</groupId>
          <artifactId>neo4j-java-driver</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <version>5.7.2</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <version>3.20.2</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <finalName>favorite-coffee</finalName>
    <plugins>
      <plugin>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.0.0-M5</version>
      </plugin>
      <plugin>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>3.0.0-M5</version>
      </plugin>
    </plugins>
  </build>
</project>
