<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <artifactId>trading-gatling</artifactId>

  <parent>
    <groupId>fr.ymanvieu.trading</groupId>
    <artifactId>trading</artifactId>
    <version>5.0.0-SNAPSHOT</version>
  </parent>


  <properties>
    <gatling.version>3.10.2</gatling.version>
    <gatling-maven-plugin.version>4.7.0</gatling-maven-plugin.version>
    <scala-maven-plugin.version>4.8.1</scala-maven-plugin.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
          <exclusions>
        <exclusion>
          <groupId>org.apiguardian</groupId>
          <artifactId>apiguardian-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.junit.jupiter</groupId>
          <artifactId>junit-jupiter-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.junit.platform</groupId>
          <artifactId>junit-platform-commons</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.opentest4j</groupId>
          <artifactId>opentest4j</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>io.gatling.highcharts</groupId>
      <artifactId>gatling-charts-highcharts</artifactId>
      <version>${gatling.version}</version>
      <scope>test</scope>
          <exclusions>
        <exclusion>
          <groupId>ch.qos.logback</groupId>
          <artifactId>logback-classic</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.github.spotbugs</groupId>
          <artifactId>spotbugs-annotations</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.typesafe</groupId>
          <artifactId>config</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.typesafe.scala-logging</groupId>
          <artifactId>scala-logging_2.13</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.gatling</groupId>
          <artifactId>gatling-core</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.gatling</groupId>
          <artifactId>gatling-core-java</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.gatling</groupId>
          <artifactId>gatling-http</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.gatling</groupId>
          <artifactId>gatling-mqtt</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.gatling</groupId>
          <artifactId>gatling-netty-util</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.gatling</groupId>
          <artifactId>gatling-shared-util_2.13</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-buffer</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-common</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-handler</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-resolver</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-resolver-dns</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-tcnative-boringssl-static</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-tcnative-classes</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-transport</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-transport-native-epoll</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-transport-native-unix-common</artifactId>
        </exclusion>
        <exclusion>
          <groupId>net.sf.saxon</groupId>
          <artifactId>Saxon-HE</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.jodd</groupId>
          <artifactId>jodd-util</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.scala-lang</groupId>
          <artifactId>scala-library</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.scala-lang</groupId>
          <artifactId>scala-reflect</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.scala-lang.modules</groupId>
          <artifactId>scala-parser-combinators_2.13</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.slf4j</groupId>
          <artifactId>slf4j-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>net.alchim31.maven</groupId>
        <artifactId>scala-maven-plugin</artifactId>
        <version>${scala-maven-plugin.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>testCompile</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <scalaVersion>2.13.12</scalaVersion>
        </configuration>
      </plugin>
      <plugin>
        <groupId>io.gatling</groupId>
        <artifactId>gatling-maven-plugin</artifactId>
        <version>${gatling-maven-plugin.version}</version>
        <configuration>
          <simulationsFolder>src/test/scala</simulationsFolder>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
