<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.benchmark</groupId>
        <artifactId>artificial-reflection-benchmark</artifactId>
        <version>1.0.0</version>
    </parent>
    <artifactId>binding-serviceloader</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>s1-spi-helper</module>
        <module>s1-transitive-unused</module>
        <module>s1-spi-impl</module>
        <module>s1-unused-direct</module>
        <module>s1-app</module>
    </modules>
</project>
