name: gitlab-panorama

services:
  gitlab-panorama:
    build: .
    container_name: gitlab-panorama
    ports:
      - "8080:8080"
    environment:
      GITLAB_TOKEN: "dummy_token_for_bean_wiring"
      INIT_COLLECT_FROM_GITLAB: "false"
      INIT_LOAD_FROM_STORAGE: "false"
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 48
      start_period: 30s
